// src/utils/stores.js — lista de lojas compartilhada entre Register e Profile

export const LOJAS_PROPRIAS = [
  'BISCOITE ABC SHOPPING','BISCOITÊ AEROPORTO DE GUARULHOS','BISCOITE ALPHAVILLE',
  'BISCOITE ANALIA FRANCO SHOPPING','BISCOITE BOSSA NOVA RJ','BISCOITE BOURBON',
  'BISCOITE BUTANTA SHOPPING','BISCOITE CASA CULTURA HIGIENÓPOLIS','BISCOITE CATARINA OUTLET',
  'BISCOITE CENTER NORTE','BISCOITE COLINAS','BISCOITE ECOMMERCE DIGITAL','BISCOITE ELDORADO',
  'BISCOITE GAVEA RJ','BISCOITE HCOR','BISCOITE INTERNACIONAL','BISCOITE ITAU PAULISTA',
  'BISCOITE JARDIM SUL','BISCOITE LEBLON RJ','BISCOITE METROPOLE','BISCOITE MOOCA',
  'BISCOITE MORUMBI QSQ','BISCOITE MORUMBI TOWN','BISCOITE NITEROI RJ',
  'BISCOITE NORTE SHOPPING RJ','BISCOITE NOVA AMERICA RJ','BISCOITE PAMPLONA',
  'BISCOITE PENHA SHOPPING','BISCOITE PLAZA SUL','BISCOITE RIO DESIGN RJ',
  'BISCOITE RIOSUL RJ','BISCOITE SAO BERNARDO SHOPPING','BISCOITE SP MARKET',
  'BISCOITE TABOAO DA SERRA','BISCOITE TAMBORE','BISCOITE TIETE PLAZA',
  'BISCOITE TIJUCA RJ','BISCOITE TRAILER','BISCOITE VILA OLIMPIA','BISCOITE VILLA LOBOS',
];

export const LOJAS_FRANQUIA = [
  'FRANQUIA - BISCOITE ALAGOAS MACEIO','FRANQUIA - BISCOITE AURORA SHOPPING',
  'FRANQUIA - BISCOITE BAHIA SHOP','FRANQUIA - BISCOITE BALNEARIO CAMBORIU SHOPPING',
  'FRANQUIA - BISCOITE BELÉM','FRANQUIA - BISCOITE BH SHOPPING',
  'FRANQUIA - BISCOITE BOULEVARD BH','FRANQUIA - BISCOITE BURITI RIO VERDE GO',
  'FRANQUIA - BISCOITE CAMBUI','FRANQUIA - BISCOITE CAMPINAS',
  'FRANQUIA - BISCOITE CAMPO GRANDE MS','FRANQUIA - BISCOITE CATUAI CASCAVEL SHOP',
  'FRANQUIA - BISCOITE CIDADE SP','FRANQUIA - BISCOITE DIAMOND MALL',
  'FRANQUIA - BISCOITE DOM PEDRO','FRANQUIA - BISCOITE ESTACAO CUIABA',
  'FRANQUIA - BISCOITE GALLERIA','FRANQUIA - BISCOITE GRAND PLAZA',
  'FRANQUIA - BISCOITE GRAO PARA','FRANQUIA - BISCOITE IBIRAPUERA SHOPPING',
  'FRANQUIA - BISCOITE INDEPENDENCIA MG','FRANQUIA - BISCOITE JOCKEY PLAZA SHOPPING',
  'FRANQUIA - BISCOITE JUNDIAÍ','FRANQUIA - BISCOITE MANAUARA SHOPPING',
  'FRANQUIA - BISCOITE MAXI JUNDIAI','FRANQUIA - BISCOITE MOGI',
  'FRANQUIA - BISCOITE MUELLER CURITIBA','FRANQUIA - BISCOITE PANTANAL SHOP',
  'FRANQUIA - BISCOITE PARALELA SHOPPING','FRANQUIA - BISCOITE PATIO BATEL',
  'FRANQUIA - BISCOITE PATIO PAULISTA','FRANQUIA - BISCOITE PERDIZES',
  'FRANQUIA - BISCOITE PIRACICABA','FRANQUIA - BISCOITE RIBEIRÃO PRETO IGUATEMI SHOP',
  'FRANQUIA - BISCOITE RIO POTY SHOP PIAUI','FRANQUIA - BISCOITE SANTA CRUZ',
  'FRANQUIA - BISCOITE SÃO JOSE DO RIO PRETO','FRANQUIA - BISCOITE SOROCABA',
  'FRANQUIA - BISCOITE SP MARKET SHOP','FRANQUIA - BISCOITE TATUAPÉ METRO SHOPPING',
];

export const TODAS_LOJAS = [...LOJAS_PROPRIAS, ...LOJAS_FRANQUIA];
